<?php

use \Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function sph_install() {
  include_once DRUPAL_ROOT . '/core/profiles/standard/standard.install';
  standard_install();
  $keywords = ['Developer', 'Team lead', 'Manager'];
  foreach ($keywords as $keyword) {
    Term::create([
      'name' => $keyword,
      'vid' => 'keywords',
    ])->save();
  }
}